export const USERS = {
    INIT: {
        IDLE: "USERS_INIT_IDLE",
        SUCCESS: "USERS_INIT_SUCCESS",
        FAILURE: "USERS_INIT_FAILURE",
    },
    ADD: {
        IDLE: "USERS_ADD_IDLE",
        SUCCESS: "USERS_ADD_SUCCESS",
        FAILURE: "USERS_ADD_FAILURE",
    },
    DELETE: {
        IDLE: "USERS_DELETE_IDLE",
        SUCCESS: "USERS_DELETE_SUCCESS",
        FAILURE: "USERS_DELETE_FAILURE",
    },
    EDIT: {
        IDLE: "USERS_EDIT_IDLE",
        SUCCESS: "USERS_EDIT_SUCCESS",
        FAILURE: "USERS_EDIT_FAILURE",
    },
    ADD_PAYMENT: {
        IDLE: "USERS_ADD_PAYMENT_IDLE",
    },
    SEND_HOMEWORK: {
        IDLE: "USERS_SEND_HOMEWORK_IDLE",
    }
};
